/**
 * Common/folk nicknames for a curated set of well-known named stars,
 * keyed by the star's HYG proper name — the same key `STAR_CONTENT`
 * uses. E.g. Polaris is commonly called "the North Star." Not
 * exhaustive: only genuinely well-known nicknames someone would
 * plausibly search by, not an attempt to invent a nickname for every
 * named star (most have none) — Bayer/Flamsteed designations are
 * already in the HYG catalog's own `names[]` array and searchable
 * without this.
 */
export const STAR_ALIASES: Record<string, string[]> = {
  Polaris: ['North Star', 'Pole Star', 'Lodestar'],
  Sirius: ['Dog Star'],
  Procyon: ['Little Dog Star'],
  Vega: ['Harp Star'],
  Capella: ['Goat Star'],
  Aldebaran: ['Eye of the Bull'],
  Antares: ['Heart of the Scorpion', 'Rival of Mars'],
  Regulus: ['Heart of the Lion', 'Little King'],
  Deneb: ['Tail of the Swan'],
  Betelgeuse: ['Armpit of the Giant'],
  Bellatrix: ['Amazon Star'],
  Dubhe: ['Pointer Star'],
  Merak: ['Pointer Star'],
}

/**
 * Common English translation for every one of the 88 IAU
 * constellations, plus a well-known informal nickname where one
 * genuinely exists (e.g. Ursa Major as "the Big Dipper"), keyed by the
 * same 3-letter abbreviation used everywhere else in this codebase
 * (`CONSTELLATION_NAMES`, `Constellation.id`, ...).
 */
export const CONSTELLATION_ALIASES: Record<string, string[]> = {
  And: ['The Chained Princess'],
  Ant: ['The Air Pump'],
  Aps: ['The Bird of Paradise'],
  Aqr: ['The Water Bearer'],
  Aql: ['The Eagle'],
  Ara: ['The Altar'],
  Ari: ['The Ram'],
  Aur: ['The Charioteer'],
  Boo: ['The Herdsman', 'The Ploughman'],
  Cae: ['The Chisel'],
  Cam: ['The Giraffe'],
  Cnc: ['The Crab'],
  CVn: ['The Hunting Dogs'],
  CMa: ['The Great Dog'],
  CMi: ['The Little Dog'],
  Cap: ['The Sea Goat'],
  Car: ['The Keel'],
  Cas: ['The Queen'],
  Cen: ['The Centaur'],
  Cep: ['The King'],
  Cet: ['The Whale', 'The Sea Monster'],
  Cha: ['The Chameleon'],
  Cir: ['The Compasses'],
  Col: ['The Dove'],
  Com: ["Berenice's Hair"],
  CrA: ['The Southern Crown'],
  CrB: ['The Northern Crown'],
  Crv: ['The Crow'],
  Crt: ['The Cup'],
  Cru: ['The Southern Cross'],
  Cyg: ['The Swan', 'Northern Cross'],
  Del: ['The Dolphin'],
  Dor: ['The Swordfish'],
  Dra: ['The Dragon'],
  Equ: ['The Little Horse', 'The Foal'],
  Eri: ['The River'],
  For: ['The Furnace'],
  Gem: ['The Twins'],
  Gru: ['The Crane'],
  Her: ['The Kneeler'],
  Hor: ['The Pendulum Clock'],
  Hya: ['The Water Snake'],
  Hyi: ['The Lesser Water Snake'],
  Ind: ['The Indian'],
  Lac: ['The Lizard'],
  Leo: ['The Lion'],
  LMi: ['The Little Lion'],
  Lep: ['The Hare'],
  Lib: ['The Scales'],
  Lup: ['The Wolf'],
  Lyn: ['The Lynx'],
  Lyr: ['The Lyre', 'The Harp'],
  Men: ['The Table Mountain'],
  Mic: ['The Microscope'],
  Mon: ['The Unicorn'],
  Mus: ['The Fly'],
  Nor: ["The Carpenter's Square"],
  Oct: ['The Octant'],
  Oph: ['The Serpent Bearer', 'The Serpent Holder'],
  Ori: ['The Hunter'],
  Pav: ['The Peacock'],
  Peg: ['The Winged Horse'],
  Per: ['The Hero'],
  Phe: ['The Phoenix'],
  Pic: ["The Painter's Easel"],
  Psc: ['The Fish', 'The Fishes'],
  PsA: ['The Southern Fish'],
  Pup: ['The Stern'],
  Pyx: ['The Compass'],
  Ret: ['The Reticle', 'The Net'],
  Sge: ['The Arrow'],
  Sgr: ['The Archer'],
  Sco: ['The Scorpion'],
  Scl: ['The Sculptor'],
  Sct: ['The Shield'],
  Ser: ['The Serpent'],
  Sex: ['The Sextant'],
  Tau: ['The Bull'],
  Tel: ['The Telescope'],
  Tri: ['The Triangle'],
  TrA: ['The Southern Triangle'],
  Tuc: ['The Toucan'],
  UMa: ['The Great Bear', 'Big Dipper', 'The Plough'],
  UMi: ['The Little Bear', 'Little Dipper'],
  Vel: ['The Sails'],
  Vir: ['The Maiden', 'The Virgin'],
  Vol: ['The Flying Fish'],
  Vul: ['The Fox'],
}
